name: Build And Test

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        if: matrix.os != 'windows-latest'

      - name: Install Playwright browsers
        run: ./gradlew installPlaywright --no-daemon
        shell: bash

      - name: Run unit tests
        run: ./gradlew unitTest --no-daemon
        shell: bash

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build JAR
        run: ./gradlew bootJar --no-daemon

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/libs/*-[0-9]*.jar
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
